/**
 * In-memory task store for orchestration.
 * Tasks are ephemeral — they live only while the server runs.
 * Persistence is handled by the frontend via Supabase.
 *
 * Supports:
 * - Event buffer for SSE replay on reconnection
 * - Listener registry for live SSE subscriptions
 * - Child process reference for kill-switch
 */

import type { ChildProcess } from 'child_process';

export interface TaskSSEEvent {
  event: string;
  data: unknown;
  timestamp: string;
}

export interface ExecutionPlanStep {
  id: string;
  squadId: string;
  agentId: string;
  agentName: string;
  squadName: string;
  task: string;
  dependsOn: string[];
  estimatedDuration?: string;
}

export interface ExecutionPlan {
  summary: string;
  reasoning: string;
  steps: ExecutionPlanStep[];
  estimatedDuration?: string;
}

export interface StoredTask {
  id: string;
  demand: string;
  status: 'pending' | 'analyzing' | 'planning' | 'awaiting_approval' | 'executing' | 'completed' | 'failed';
  squads: Array<{
    squadId: string;
    chief: string;
    agentCount: number;
    agents: Array<{ id: string; name: string }>;
  }>;
  outputs: Array<{
    stepId: string;
    stepName: string;
    output: Record<string, unknown>;
  }>;
  /** Execution plan generated by the orchestrator, pending user approval */
  plan?: ExecutionPlan;
  /** Revision feedback from user (for re-planning) */
  planFeedback?: string;
  createdAt: string;
  startedAt?: string;
  completedAt?: string;
  error?: string;
  /** All SSE events emitted during execution (for replay) */
  eventBuffer: TaskSSEEvent[];
  /** Live SSE subscribers */
  listeners: Set<(event: TaskSSEEvent) => void>;
  /** Reference to the Claude CLI child process (for kill-switch) */
  childProcess?: ChildProcess;
}

// Use globalThis to survive Next.js hot-reloads in dev mode
const globalForTasks = globalThis as unknown as { __taskStore?: Map<string, StoredTask> };
if (!globalForTasks.__taskStore) {
  globalForTasks.__taskStore = new Map();
}
const tasks = globalForTasks.__taskStore;

// Track last streaming chunk index per stepId (for compaction)
const lastChunkIndex = new Map<string, Map<string, number>>();

export function createTask(id: string, demand: string): StoredTask {
  const task: StoredTask = {
    id,
    demand,
    status: 'pending',
    squads: [],
    outputs: [],
    createdAt: new Date().toISOString(),
    eventBuffer: [],
    listeners: new Set(),
  };
  tasks.set(id, task);
  lastChunkIndex.set(id, new Map());
  return task;
}

export function getTask(id: string): StoredTask | undefined {
  return tasks.get(id);
}

export function updateTask(id: string, updates: Partial<StoredTask>): StoredTask | undefined {
  const task = tasks.get(id);
  if (!task) return undefined;
  Object.assign(task, updates);
  return task;
}

export function listTasks(limit = 50): StoredTask[] {
  return Array.from(tasks.values())
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, limit);
}

/**
 * Push an SSE event to the task's buffer and notify all live listeners.
 * Streaming chunk events are compacted: only the last chunk per stepId is kept.
 */
export function pushEvent(taskId: string, event: string, data: unknown): void {
  const task = tasks.get(taskId);
  if (!task) return;

  const sseEvent: TaskSSEEvent = {
    event,
    data,
    timestamp: new Date().toISOString(),
  };

  // Compact streaming chunks: replace previous chunk for same stepId
  if (event === 'step:streaming:chunk') {
    const stepId = (data as Record<string, unknown>)?.stepId as string;
    if (stepId) {
      const chunkMap = lastChunkIndex.get(taskId);
      if (chunkMap) {
        const prevIndex = chunkMap.get(stepId);
        if (prevIndex !== undefined) {
          // Replace in-place
          task.eventBuffer[prevIndex] = sseEvent;
        } else {
          chunkMap.set(stepId, task.eventBuffer.length);
          task.eventBuffer.push(sseEvent);
        }
      } else {
        task.eventBuffer.push(sseEvent);
      }
    } else {
      task.eventBuffer.push(sseEvent);
    }
  } else {
    task.eventBuffer.push(sseEvent);
  }

  // Notify all live listeners
  for (const listener of task.listeners) {
    try { listener(sseEvent); } catch { /* listener error */ }
  }
}

/**
 * Subscribe to live SSE events for a task.
 * Returns an unsubscribe function.
 */
export function subscribe(taskId: string, callback: (event: TaskSSEEvent) => void): () => void {
  const task = tasks.get(taskId);
  if (!task) return () => {};

  task.listeners.add(callback);
  return () => { task.listeners.delete(callback); };
}

/**
 * Get the full event buffer for replay.
 */
export function getEventBuffer(taskId: string): TaskSSEEvent[] {
  return tasks.get(taskId)?.eventBuffer || [];
}

/**
 * Kill the running Claude CLI process for a task.
 */
export function killTask(taskId: string): boolean {
  const task = tasks.get(taskId);
  if (!task?.childProcess) return false;
  try {
    task.childProcess.kill('SIGTERM');
    return true;
  } catch {
    return false;
  }
}

// Cleanup old tasks every 10 minutes (TTL: 2 hours)
const TASK_TTL_MS = parseInt(process.env.TASK_TTL_MS || String(2 * 60 * 60 * 1000), 10);
setInterval(() => {
  const now = Date.now();
  for (const [id, task] of tasks) {
    const age = now - new Date(task.createdAt).getTime();
    if (age > TASK_TTL_MS && (task.status === 'completed' || task.status === 'failed')) {
      tasks.delete(id);
      lastChunkIndex.delete(id);
    }
  }
}, 10 * 60 * 1000);
