import type { WorkflowMission, WorkflowOperation, AgentTool } from './types';

// Tool definitions
const AGENT_TOOLS: Record<string, AgentTool[]> = {
  orchestrator: [
    { id: 'api', name: 'API', description: 'Integração com APIs externas', connected: true },
    { id: 'slack', name: 'Slack', description: 'Comunicação com equipe', connected: true },
    { id: 'notion', name: 'Notion', description: 'Documentação e wikis', connected: true },
    { id: 'calendar', name: 'Calendar', description: 'Agendamento de tarefas', connected: true },
    { id: 'analytics', name: 'Analytics', description: 'Métricas e dashboards', connected: true },
  ],
  copywriting: [
    { id: 'web-search', name: 'Web Search', description: 'Pesquisa na internet', connected: true },
    { id: 'web-scraper', name: 'Web Scraper', description: 'Extração de conteúdo', connected: true },
    { id: 'docs', name: 'Google Docs', description: 'Edição de documentos', connected: true },
    { id: 'notion', name: 'Notion', description: 'Base de conhecimento', connected: true },
    { id: 'analytics', name: 'Analytics', description: 'Dados de SEO', connected: false },
  ],
  design: [
    { id: 'figma', name: 'Figma', description: 'Design de interfaces', connected: true },
    { id: 'image-gen', name: 'Image Gen', description: 'Geração de imagens AI', connected: true },
    { id: 'web-scraper', name: 'Web Scraper', description: 'Referências visuais', connected: true },
    { id: 'file-system', name: 'File System', description: 'Gerenciamento de assets', connected: true },
    { id: 'notion', name: 'Notion', description: 'Brand guidelines', connected: true },
  ],
  creator: [
    { id: 'image-gen', name: 'Image Gen', description: 'Criação de visuais', connected: true },
    { id: 'web-search', name: 'Web Search', description: 'Pesquisa de trends', connected: true },
    { id: 'analytics', name: 'Analytics', description: 'Métricas de conteúdo', connected: true },
    { id: 'calendar', name: 'Calendar', description: 'Calendário editorial', connected: true },
    { id: 'slack', name: 'Slack', description: 'Comunicação', connected: false },
  ],
};

// Mock data for simple workflow
const createSimpleMission = (): WorkflowMission => ({
  id: 'mission-001',
  name: 'Campanha de Lançamento Q1',
  description: 'Criação completa de campanha incluindo copy, design e conteúdo para redes sociais',
  status: 'in-progress',
  startedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  progress: 45,
  currentNode: 'node-copy-1',
  tokens: { input: 12450, output: 8320, total: 20770 },
  estimatedTimeRemaining: 420, // 7 minutes
  nodes: [
    {
      id: 'node-start',
      type: 'start',
      label: 'Início',
      status: 'completed',
      position: { x: 100, y: 300 },
    },
    {
      id: 'node-orchestrator',
      type: 'agent',
      label: 'Orquestração',
      agentName: 'Orion',
      squadType: 'orchestrator',
      status: 'completed',
      position: { x: 250, y: 300 },
      progress: 100,
      currentAction: 'Tarefa concluída',
      request: 'Coordenar a criação de uma campanha de lançamento completa para o produto X, incluindo headlines, body copy, design visual e conteúdo para redes sociais.',
      startedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      completedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
      tools: AGENT_TOOLS.orchestrator,
      tokens: { input: 2150, output: 1820, total: 3970 },
      estimatedDuration: 60,
      todos: [
        { id: 't1', text: 'Analisar briefing do cliente', status: 'completed' },
        { id: 't2', text: 'Identificar dependências entre tarefas', status: 'completed' },
        { id: 't3', text: 'Distribuir tarefas para agents especializados', status: 'completed' },
        { id: 't4', text: 'Monitorar progresso geral', status: 'completed' },
      ],
      files: [
        { id: 'f1', name: 'task-distribution.json', type: 'json', size: '2.1 KB', createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString() },
        { id: 'f2', name: 'workflow-plan.md', type: 'markdown', size: '1.5 KB', createdAt: new Date(Date.now() - 4.5 * 60 * 1000).toISOString() },
      ],
      output: 'Workflow configurado com sucesso. 5 agents alocados, 4 tarefas principais distribuídas.',
    },
    {
      id: 'node-copy-1',
      type: 'agent',
      label: 'Headlines',
      agentName: 'Luna',
      squadType: 'copywriting',
      status: 'active',
      position: { x: 420, y: 180 },
      progress: 65,
      currentAction: 'Escrevendo variação #3...',
      request: 'Criar 5 opções de headline impactantes para a landing page do produto X. Foco em conversão e benefícios principais. Tom: profissional mas acessível.',
      startedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
      tools: AGENT_TOOLS.copywriting,
      tokens: { input: 3200, output: 2150, total: 5350 },
      estimatedDuration: 180,
      todos: [
        { id: 't1', text: 'Analisar público-alvo e tom de voz', status: 'completed' },
        { id: 't2', text: 'Pesquisar headlines de concorrentes', status: 'completed' },
        { id: 't3', text: 'Criar headline #1 - Foco em benefício principal', status: 'completed' },
        { id: 't4', text: 'Criar headline #2 - Foco em urgência', status: 'completed' },
        { id: 't5', text: 'Criar headline #3 - Foco em prova social', status: 'in-progress' },
        { id: 't6', text: 'Criar headline #4 - Foco em exclusividade', status: 'pending' },
        { id: 't7', text: 'Criar headline #5 - Variação criativa', status: 'pending' },
      ],
      files: [
        { id: 'f1', name: 'headlines-v1.md', type: 'markdown', size: '1.8 KB', createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString() },
        { id: 'f2', name: 'competitor-research.txt', type: 'text', size: '3.2 KB', createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString() },
      ],
    },
    {
      id: 'node-copy-2',
      type: 'agent',
      label: 'Body Copy',
      agentName: 'Atlas',
      squadType: 'copywriting',
      status: 'waiting',
      position: { x: 420, y: 420 },
      progress: 0,
      currentAction: 'Aguardando headlines...',
      request: 'Desenvolver o body copy da landing page com base nas headlines aprovadas. Incluir: introdução, benefícios, features, prova social e CTA.',
      tools: AGENT_TOOLS.copywriting,
      tokens: { input: 0, output: 0, total: 0 },
      estimatedDuration: 240,
      todos: [
        { id: 't1', text: 'Aguardar headlines finalizadas', status: 'in-progress' },
        { id: 't2', text: 'Desenvolver introdução', status: 'pending' },
        { id: 't3', text: 'Escrever seção de benefícios', status: 'pending' },
        { id: 't4', text: 'Detalhar features do produto', status: 'pending' },
        { id: 't5', text: 'Criar seção de prova social', status: 'pending' },
        { id: 't6', text: 'Escrever CTAs', status: 'pending' },
      ],
      files: [],
    },
    {
      id: 'node-design',
      type: 'agent',
      label: 'Visual Design',
      agentName: 'Maya',
      squadType: 'design',
      status: 'waiting',
      position: { x: 600, y: 300 },
      progress: 0,
      currentAction: 'Aguardando copy...',
      request: 'Criar o design visual da landing page seguindo o brand guideline. Incluir hero section, layout de benefícios, e elementos visuais de suporte.',
      tools: AGENT_TOOLS.design,
      tokens: { input: 0, output: 0, total: 0 },
      estimatedDuration: 300,
      todos: [
        { id: 't1', text: 'Aguardar copy finalizado', status: 'in-progress' },
        { id: 't2', text: 'Criar hero section', status: 'pending' },
        { id: 't3', text: 'Desenvolver layout de benefícios', status: 'pending' },
        { id: 't4', text: 'Criar elementos visuais de suporte', status: 'pending' },
        { id: 't5', text: 'Adaptar para versão mobile', status: 'pending' },
      ],
      files: [],
    },
    {
      id: 'node-creator',
      type: 'agent',
      label: 'Conteúdo Social',
      agentName: 'Phoenix',
      squadType: 'creator',
      status: 'idle',
      position: { x: 780, y: 300 },
      progress: 0,
      request: 'Criar pacote de conteúdo para redes sociais: 5 posts para Instagram, 3 para LinkedIn, e 2 vídeos curtos para Reels/TikTok.',
      tools: AGENT_TOOLS.creator,
      tokens: { input: 0, output: 0, total: 0 },
      estimatedDuration: 360,
      todos: [
        { id: 't1', text: 'Aguardar assets de design', status: 'pending' },
        { id: 't2', text: 'Criar 5 posts para Instagram', status: 'pending' },
        { id: 't3', text: 'Criar 3 posts para LinkedIn', status: 'pending' },
        { id: 't4', text: 'Desenvolver roteiro vídeo #1', status: 'pending' },
        { id: 't5', text: 'Desenvolver roteiro vídeo #2', status: 'pending' },
      ],
      files: [],
    },
    {
      id: 'node-review',
      type: 'checkpoint',
      label: 'Revisão Final',
      status: 'idle',
      position: { x: 920, y: 300 },
      request: 'Ponto de revisão para aprovação de todos os materiais antes da entrega final.',
      todos: [
        { id: 't1', text: 'Revisar todos os materiais', status: 'pending' },
        { id: 't2', text: 'Verificar consistência de marca', status: 'pending' },
        { id: 't3', text: 'Aprovar ou solicitar ajustes', status: 'pending' },
      ],
    },
    {
      id: 'node-end',
      type: 'end',
      label: 'Concluído',
      status: 'idle',
      position: { x: 1050, y: 300 },
    },
  ],
  edges: [
    { id: 'edge-1', source: 'node-start', target: 'node-orchestrator', status: 'completed' },
    { id: 'edge-2', source: 'node-orchestrator', target: 'node-copy-1', status: 'active', animated: true },
    { id: 'edge-3', source: 'node-orchestrator', target: 'node-copy-2', status: 'active', animated: true },
    { id: 'edge-4', source: 'node-copy-1', target: 'node-design', status: 'idle' },
    { id: 'edge-5', source: 'node-copy-2', target: 'node-design', status: 'idle' },
    { id: 'edge-6', source: 'node-design', target: 'node-creator', status: 'idle' },
    { id: 'edge-7', source: 'node-creator', target: 'node-review', status: 'idle' },
    { id: 'edge-8', source: 'node-review', target: 'node-end', status: 'idle' },
  ],
  agents: [
    { id: 'agent-1', name: 'Orion', squadType: 'orchestrator', role: 'Orchestrator Chief', status: 'completed', currentTask: 'Distribuição concluída' },
    { id: 'agent-2', name: 'Luna', squadType: 'copywriting', role: 'Creative Writer', status: 'working', currentTask: 'Criando headlines' },
    { id: 'agent-3', name: 'Atlas', squadType: 'copywriting', role: 'Content Strategist', status: 'waiting', currentTask: 'Aguardando' },
    { id: 'agent-4', name: 'Maya', squadType: 'design', role: 'Visual Designer', status: 'waiting', currentTask: 'Aguardando copy' },
    { id: 'agent-5', name: 'Phoenix', squadType: 'creator', role: 'Content Creator', status: 'waiting', currentTask: 'Aguardando assets' },
  ],
});

// Complex multi-squad workflow
const createComplexMission = (): WorkflowMission => ({
  id: 'mission-002',
  name: 'Lançamento de Produto Completo',
  description: 'Estratégia integrada de lançamento com múltiplos squads: pesquisa de mercado, branding, conteúdo multiplataforma, automação de marketing e análise de performance.',
  status: 'in-progress',
  startedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  progress: 35,
  currentNode: 'node-research',
  tokens: { input: 45200, output: 32100, total: 77300 },
  estimatedTimeRemaining: 1800, // 30 minutes
  nodes: [
    // Start
    { id: 'node-start', type: 'start', label: 'Início', status: 'completed', position: { x: 50, y: 350 } },

    // Phase 1: Orchestration & Research (Row 1)
    {
      id: 'node-orchestrator-main',
      type: 'agent',
      label: 'Orquestração Principal',
      agentName: 'Orion',
      squadType: 'orchestrator',
      status: 'completed',
      position: { x: 180, y: 350 },
      progress: 100,
      tools: AGENT_TOOLS.orchestrator,
      tokens: { input: 4500, output: 3200, total: 7700 },
      estimatedDuration: 120,
      request: 'Coordenar lançamento completo do produto, gerenciando 4 squads e 12 agents simultaneamente.',
      output: 'Plano de execução definido com 4 fases e 15 entregas.',
      todos: [
        { id: 't1', text: 'Mapear todas as dependências', status: 'completed' },
        { id: 't2', text: 'Alocar agents por especialidade', status: 'completed' },
        { id: 't3', text: 'Definir checkpoints de revisão', status: 'completed' },
      ],
      files: [
        { id: 'f1', name: 'master-plan.md', type: 'markdown', size: '4.2 KB', createdAt: new Date(Date.now() - 14 * 60 * 1000).toISOString() },
      ],
    },

    // Phase 2: Research & Strategy (Parallel branch 1)
    {
      id: 'node-research',
      type: 'agent',
      label: 'Pesquisa de Mercado',
      agentName: 'Nova',
      squadType: 'copywriting',
      status: 'active',
      position: { x: 350, y: 150 },
      progress: 70,
      tools: [
        { id: 'web-search', name: 'Web Search', connected: true },
        { id: 'web-scraper', name: 'Web Scraper', connected: true },
        { id: 'analytics', name: 'Analytics', connected: true },
        { id: 'sheets', name: 'Sheets', connected: true },
      ],
      tokens: { input: 8200, output: 5400, total: 13600 },
      estimatedDuration: 300,
      currentAction: 'Analisando dados de concorrentes...',
      request: 'Realizar pesquisa completa de mercado, análise de concorrentes e identificação de oportunidades.',
      todos: [
        { id: 't1', text: 'Mapear concorrentes diretos', status: 'completed' },
        { id: 't2', text: 'Analisar posicionamento de preço', status: 'completed' },
        { id: 't3', text: 'Identificar gaps de mercado', status: 'in-progress' },
        { id: 't4', text: 'Compilar relatório final', status: 'pending' },
      ],
      files: [
        { id: 'f1', name: 'competitor-analysis.xlsx', type: 'code', size: '156 KB', createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString() },
      ],
    },
    {
      id: 'node-persona',
      type: 'agent',
      label: 'Personas & ICP',
      agentName: 'Atlas',
      squadType: 'copywriting',
      status: 'active',
      position: { x: 350, y: 300 },
      progress: 55,
      tools: AGENT_TOOLS.copywriting,
      tokens: { input: 5600, output: 4100, total: 9700 },
      estimatedDuration: 240,
      currentAction: 'Definindo buyer personas...',
      request: 'Criar personas detalhadas e definir ICP (Ideal Customer Profile) baseado em dados.',
      todos: [
        { id: 't1', text: 'Analisar dados demográficos', status: 'completed' },
        { id: 't2', text: 'Criar persona primária', status: 'completed' },
        { id: 't3', text: 'Criar persona secundária', status: 'in-progress' },
        { id: 't4', text: 'Documentar jornada do cliente', status: 'pending' },
      ],
      files: [
        { id: 'f1', name: 'persona-primaria.md', type: 'markdown', size: '2.8 KB', createdAt: new Date(Date.now() - 8 * 60 * 1000).toISOString() },
      ],
    },

    // Phase 2: Brand & Visual (Parallel branch 2)
    {
      id: 'node-brand-strategy',
      type: 'agent',
      label: 'Estratégia de Marca',
      agentName: 'Luna',
      squadType: 'copywriting',
      status: 'active',
      position: { x: 350, y: 450 },
      progress: 80,
      tools: AGENT_TOOLS.copywriting,
      tokens: { input: 6800, output: 5200, total: 12000 },
      estimatedDuration: 180,
      currentAction: 'Finalizando tom de voz...',
      request: 'Desenvolver estratégia de marca, posicionamento e tom de voz.',
      todos: [
        { id: 't1', text: 'Definir proposta de valor', status: 'completed' },
        { id: 't2', text: 'Criar manifesto da marca', status: 'completed' },
        { id: 't3', text: 'Definir tom de voz', status: 'in-progress' },
        { id: 't4', text: 'Guidelines de comunicação', status: 'pending' },
      ],
      files: [
        { id: 'f1', name: 'brand-manifesto.md', type: 'markdown', size: '3.5 KB', createdAt: new Date(Date.now() - 7 * 60 * 1000).toISOString() },
        { id: 'f2', name: 'value-proposition.md', type: 'markdown', size: '1.2 KB', createdAt: new Date(Date.now() - 9 * 60 * 1000).toISOString() },
      ],
    },
    {
      id: 'node-visual-identity',
      type: 'agent',
      label: 'Identidade Visual',
      agentName: 'Maya',
      squadType: 'design',
      status: 'waiting',
      position: { x: 350, y: 600 },
      progress: 0,
      tools: AGENT_TOOLS.design,
      tokens: { input: 0, output: 0, total: 0 },
      estimatedDuration: 360,
      currentAction: 'Aguardando estratégia de marca...',
      request: 'Criar identidade visual completa alinhada com a estratégia de marca.',
      todos: [
        { id: 't1', text: 'Aguardar brand strategy', status: 'in-progress' },
        { id: 't2', text: 'Desenvolver moodboard', status: 'pending' },
        { id: 't3', text: 'Criar paleta de cores', status: 'pending' },
        { id: 't4', text: 'Definir tipografia', status: 'pending' },
        { id: 't5', text: 'Criar elementos gráficos', status: 'pending' },
      ],
      files: [],
    },

    // Checkpoint 1
    {
      id: 'node-checkpoint-1',
      type: 'checkpoint',
      label: 'Review: Estratégia',
      status: 'idle',
      position: { x: 520, y: 350 },
      request: 'Validar pesquisa, personas, estratégia de marca e identidade visual antes de prosseguir.',
    },

    // Phase 3: Content Creation (Multiple parallel tracks)
    {
      id: 'node-copy-landing',
      type: 'agent',
      label: 'Copy Landing Page',
      agentName: 'Luna',
      squadType: 'copywriting',
      status: 'idle',
      position: { x: 680, y: 100 },
      progress: 0,
      tools: AGENT_TOOLS.copywriting,
      request: 'Criar todo o copy da landing page de lançamento.',
    },
    {
      id: 'node-copy-email',
      type: 'agent',
      label: 'Sequência de Emails',
      agentName: 'Atlas',
      squadType: 'copywriting',
      status: 'idle',
      position: { x: 680, y: 250 },
      progress: 0,
      tools: [
        ...AGENT_TOOLS.copywriting,
        { id: 'email', name: 'Email', description: 'Automação de emails', connected: true },
      ],
      request: 'Criar sequência de 7 emails para nutrição e conversão.',
    },
    {
      id: 'node-design-landing',
      type: 'agent',
      label: 'Design Landing Page',
      agentName: 'Maya',
      squadType: 'design',
      status: 'idle',
      position: { x: 680, y: 400 },
      progress: 0,
      tools: AGENT_TOOLS.design,
      request: 'Criar design completo da landing page (desktop e mobile).',
    },
    {
      id: 'node-design-ads',
      type: 'agent',
      label: 'Criativos de Ads',
      agentName: 'Zara',
      squadType: 'design',
      status: 'idle',
      position: { x: 680, y: 550 },
      progress: 0,
      tools: AGENT_TOOLS.design,
      request: 'Criar pack de criativos para Meta Ads e Google Ads.',
    },
    {
      id: 'node-social-content',
      type: 'agent',
      label: 'Conteúdo Social',
      agentName: 'Phoenix',
      squadType: 'creator',
      status: 'idle',
      position: { x: 850, y: 175 },
      progress: 0,
      tools: AGENT_TOOLS.creator,
      request: 'Criar calendário de 30 dias de conteúdo para Instagram, LinkedIn e TikTok.',
    },
    {
      id: 'node-video-scripts',
      type: 'agent',
      label: 'Roteiros de Vídeo',
      agentName: 'Echo',
      squadType: 'creator',
      status: 'idle',
      position: { x: 850, y: 325 },
      progress: 0,
      tools: [
        ...AGENT_TOOLS.creator,
        { id: 'code-interpreter', name: 'Code', description: 'Formatação de roteiros', connected: true },
      ],
      request: 'Criar roteiros para vídeo de lançamento, demo e depoimentos.',
    },

    // Checkpoint 2
    {
      id: 'node-checkpoint-2',
      type: 'checkpoint',
      label: 'Review: Conteúdo',
      status: 'idle',
      position: { x: 1000, y: 350 },
      request: 'Revisar todos os materiais de conteúdo antes da implementação.',
    },

    // Phase 4: Integration & Launch
    {
      id: 'node-integration',
      type: 'agent',
      label: 'Integração & Setup',
      agentName: 'Orion',
      squadType: 'orchestrator',
      status: 'idle',
      position: { x: 1150, y: 250 },
      progress: 0,
      tools: [
        ...AGENT_TOOLS.orchestrator,
        { id: 'api', name: 'API', description: 'Integrações', connected: true },
        { id: 'database', name: 'Database', description: 'Configuração de dados', connected: true },
      ],
      request: 'Configurar todas as integrações, automações e tracking.',
    },
    {
      id: 'node-qa',
      type: 'agent',
      label: 'QA & Testes',
      agentName: 'Sage',
      squadType: 'orchestrator',
      status: 'idle',
      position: { x: 1150, y: 450 },
      progress: 0,
      tools: [
        { id: 'web-scraper', name: 'Web Scraper', connected: true },
        { id: 'analytics', name: 'Analytics', connected: true },
        { id: 'api', name: 'API', connected: true },
      ],
      request: 'Testar todos os fluxos, links, automações e tracking.',
    },

    // Final
    {
      id: 'node-launch',
      type: 'checkpoint',
      label: 'Go Live',
      status: 'idle',
      position: { x: 1300, y: 350 },
      request: 'Aprovação final e ativação de todas as campanhas.',
    },
    { id: 'node-end', type: 'end', label: 'Lançado', status: 'idle', position: { x: 1420, y: 350 } },
  ],
  edges: [
    // Start to orchestrator
    { id: 'e1', source: 'node-start', target: 'node-orchestrator-main', status: 'completed' },

    // Orchestrator to Phase 2 (parallel)
    { id: 'e2', source: 'node-orchestrator-main', target: 'node-research', status: 'active', animated: true },
    { id: 'e3', source: 'node-orchestrator-main', target: 'node-persona', status: 'active', animated: true },
    { id: 'e4', source: 'node-orchestrator-main', target: 'node-brand-strategy', status: 'active', animated: true },
    { id: 'e5', source: 'node-orchestrator-main', target: 'node-visual-identity', status: 'idle' },

    // Brand strategy to visual identity
    { id: 'e6', source: 'node-brand-strategy', target: 'node-visual-identity', status: 'idle', label: 'depende' },

    // Phase 2 to Checkpoint 1
    { id: 'e7', source: 'node-research', target: 'node-checkpoint-1', status: 'idle' },
    { id: 'e8', source: 'node-persona', target: 'node-checkpoint-1', status: 'idle' },
    { id: 'e9', source: 'node-brand-strategy', target: 'node-checkpoint-1', status: 'idle' },
    { id: 'e10', source: 'node-visual-identity', target: 'node-checkpoint-1', status: 'idle' },

    // Checkpoint 1 to Phase 3
    { id: 'e11', source: 'node-checkpoint-1', target: 'node-copy-landing', status: 'idle' },
    { id: 'e12', source: 'node-checkpoint-1', target: 'node-copy-email', status: 'idle' },
    { id: 'e13', source: 'node-checkpoint-1', target: 'node-design-landing', status: 'idle' },
    { id: 'e14', source: 'node-checkpoint-1', target: 'node-design-ads', status: 'idle' },

    // Copy to social/video
    { id: 'e15', source: 'node-copy-landing', target: 'node-social-content', status: 'idle' },
    { id: 'e16', source: 'node-copy-landing', target: 'node-video-scripts', status: 'idle' },

    // Phase 3 to Checkpoint 2
    { id: 'e17', source: 'node-social-content', target: 'node-checkpoint-2', status: 'idle' },
    { id: 'e18', source: 'node-video-scripts', target: 'node-checkpoint-2', status: 'idle' },
    { id: 'e19', source: 'node-design-landing', target: 'node-checkpoint-2', status: 'idle' },
    { id: 'e20', source: 'node-design-ads', target: 'node-checkpoint-2', status: 'idle' },
    { id: 'e21', source: 'node-copy-email', target: 'node-checkpoint-2', status: 'idle' },

    // Checkpoint 2 to Phase 4
    { id: 'e22', source: 'node-checkpoint-2', target: 'node-integration', status: 'idle' },
    { id: 'e23', source: 'node-checkpoint-2', target: 'node-qa', status: 'idle' },

    // Phase 4 to Launch
    { id: 'e24', source: 'node-integration', target: 'node-launch', status: 'idle' },
    { id: 'e25', source: 'node-qa', target: 'node-launch', status: 'idle' },

    // Launch to End
    { id: 'e26', source: 'node-launch', target: 'node-end', status: 'idle' },
  ],
  agents: [
    { id: 'agent-1', name: 'Orion', squadType: 'orchestrator', role: 'Lead Orchestrator', status: 'completed', currentTask: 'Monitorando execução' },
    { id: 'agent-2', name: 'Nova', squadType: 'copywriting', role: 'Research Analyst', status: 'working', currentTask: 'Pesquisa de mercado' },
    { id: 'agent-3', name: 'Atlas', squadType: 'copywriting', role: 'Content Strategist', status: 'working', currentTask: 'Criando personas' },
    { id: 'agent-4', name: 'Luna', squadType: 'copywriting', role: 'Creative Writer', status: 'working', currentTask: 'Estratégia de marca' },
    { id: 'agent-5', name: 'Maya', squadType: 'design', role: 'Lead Designer', status: 'waiting', currentTask: 'Aguardando' },
    { id: 'agent-6', name: 'Zara', squadType: 'design', role: 'Visual Designer', status: 'waiting', currentTask: 'Aguardando' },
    { id: 'agent-7', name: 'Phoenix', squadType: 'creator', role: 'Content Creator', status: 'waiting', currentTask: 'Aguardando' },
    { id: 'agent-8', name: 'Echo', squadType: 'creator', role: 'Video Producer', status: 'waiting', currentTask: 'Aguardando' },
    { id: 'agent-9', name: 'Sage', squadType: 'orchestrator', role: 'QA Specialist', status: 'waiting', currentTask: 'Aguardando' },
  ],
});

// Factory function to get mission by type
export const createMockMission = (type: 'simple' | 'complex' = 'simple'): WorkflowMission => {
  return type === 'complex' ? createComplexMission() : createSimpleMission();
};

export const createMockOperations = (): WorkflowOperation[] => [
  {
    id: 'op-1',
    missionId: 'mission-001',
    agentName: 'Orion',
    squadType: 'orchestrator',
    action: 'Analisando briefing e distribuindo tarefas',
    status: 'completed',
    startedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    duration: 45,
  },
  {
    id: 'op-2',
    missionId: 'mission-001',
    agentName: 'Luna',
    squadType: 'copywriting',
    action: 'Criando headlines para landing page',
    status: 'running',
    startedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
  },
  {
    id: 'op-3',
    missionId: 'mission-001',
    agentName: 'Atlas',
    squadType: 'copywriting',
    action: 'Aguardando headlines para iniciar body copy',
    status: 'pending',
    startedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },
  {
    id: 'op-4',
    missionId: 'mission-001',
    agentName: 'Maya',
    squadType: 'design',
    action: 'Preparando templates visuais',
    status: 'pending',
    startedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
];

export { AGENT_TOOLS, createSimpleMission, createComplexMission };
